aavo

diff --git a/welcome-react/Jenkinsfile b/welcome-react/Jenkinsfile
--- a/welcome-react/Jenkinsfile
+++ b/welcome-react/Jenkinsfile
@@ -1,6 +1,60 @@
 pipeline {
     agent any
 
+    environment {
+        IMAGE_NAME = "react-app"
+        CONTAINER_NAME = "blissful_pascal"
+    }
+
+    stages {
+
+        stage('Clone Code') {
+            steps {
+                git branch: 'main',
+                    url: 'https://github.com/Hawk1509/NSDC.git'
+            }
+        }
+
+        stage('Build Docker Image') {
+            steps {
+                sh '''
+                docker build -t $IMAGE_NAME .
+                '''
+            }
+        }
+
+        stage('Stop Old Container') {
+            steps {
+                sh '''
+                docker stop $CONTAINER_NAME || true
+                docker rm $CONTAINER_NAME || true
+                '''
+            }
+        }
+
+        stage('Run Docker Container') {
+            steps {
+                sh '''
+                docker run -d \
+                  -p 5173:5173 \
+                  --name $CONTAINER_NAME \
+                  $IMAGE_NAME
+                '''
+            }
+        }
+    }
+
+    post {
+        success {
+            echo 'React app deployed using Docker successfully 🎉'
+        }
+        failure {
+            echo 'Deployment failed ❌'
+        }
+    }
+}pipeline {
+    agent any
+
     tools {
         nodejs 'NodeJS-22'
     }
@@ -32,3 +86,4 @@ pipeline {
         }
     }
 }
+
